# calc - a graphical calculator for koppi-os, running in ring 3 on microui.
# The shared rules (which objects, which include paths and why) are in
# ../microui/mui.mk.

APP = calc
OBJ = main.o

include ../microui/mui.mk
