/**
 * @file commands.c
 * @brief Built-in command interpreter for the kernel debug console.
 *
 * Parses a line typed at the kernel shell prompt and dispatches it to a
 * handler. All path handling is bounded: user input is never copied into a
 * fixed buffer without a length check.
 */

#include <lib/string.h>
#include <mm.h>
#include <kheap.h>
#include <printf.h>
#include <sched.h>
#include <vfs.h>
#include <io.h>
#include <pci.h>
#include <pci_acpi.h>
#include <pci_ac97.h>
#include <e1000.h>
#include <net.h>
#include <dhcp.h>
#include <keyboard.h>
#include <commands.h>

/** Scratch buffer used to assemble an absolute path before a VFS call. */
static char senddir[64];

/** Current working directory of the console ("" means: use DEFAULT_DEVICE). */
static char dir[64];

/** Device a relative name resolves against when no directory has been set. */
#define DEFAULT_DEVICE "/fda"

/** Sample rate, in Hz, of the tone generated by the "beep" command. */
#define BEEP_SAMPLES 44100

/**
 * @brief Print a summary of physical memory, kernel heap and control registers.
 */
void print_meminfo(void) {
    printf("Total mem: %u MB, free mem: %u MB\n",
           get_mem_size() / 1024, (get_max_blocks() - get_used_blocks()) * 4 / 1024);
    printf("Heap size: %d KB, free heap: %d KB\n",
           get_heap_size() / 1024, (get_heap_size() - get_used_heap()) / 1024);
    printf("cr0: %x cr2: %x cr3: %x\n", get_cr0(), get_cr2(), get_pdbr());
}

/**
 * @brief Locate the @p n-th space-separated argument of a command line.
 *
 * Argument 0 is the command word itself, argument 1 the first operand, and so
 * on. The returned pointer refers into @p command and is not NUL-clipped at the
 * end of the token, so the caller must stop at the next space itself.
 *
 * @param command NUL-terminated command line.
 * @param n       Zero-based argument index.
 * @return Pointer to the start of the argument, or NULL if the line has fewer
 *         than @p n arguments.
 */
char *get_argument(char *command, int n) {
    for(int i = 0; i < n; i++) {
        command = strchr(command, ' ');
        if(command) {
            command++;
        } else {
            return command;
        }
    }
    return command;
}

/**
 * @brief Compose "<dir>/<name>" into @p out without overflowing it.
 *
 * Only the first whitespace-delimited token of @p name is used, so trailing
 * command arguments are stripped automatically. The result is always NUL
 * terminated.
 *
 * @param out   Destination buffer.
 * @param outsz Size of @p out in bytes.
 * @param dir   Directory prefix (NULL is treated as "").
 * @param name  File or directory name, optionally followed by arguments.
 * @return Non-zero on success, 0 if the path had to be truncated.
 */
static int build_path(char *out, size_t outsz, const char *dir, const char *name) {
    size_t namelen = 0;
    if(name) {
        while(name[namelen] && name[namelen] != ' ') {
            namelen++;
        }
    }
    int n = snprintf(out, outsz, "%s/%.*s",
                     dir ? dir : "", (int)namelen, name ? name : "");
    return (n >= 0 && (size_t)n < outsz);
}

/**
 * @brief Resolve a user-supplied name to an absolute device path.
 *
 * A name that already contains '/' (e.g. "hda/hello") is treated as
 * device-qualified and only gets a leading '/' if missing. A bare name is
 * resolved against the console working directory, falling back to
 * DEFAULT_DEVICE when none is set, so "start hello" locates "/fda/hello".
 *
 * @param out   Destination buffer.
 * @param outsz Size of @p out in bytes.
 * @param name  File or directory name, optionally followed by arguments.
 * @return Non-zero on success, 0 if the path had to be truncated.
 */
static int resolve_path(char *out, size_t outsz, const char *name) {
    if(name && strchr((char *)name, '/')) {
        size_t len = 0;
        while(name[len] && name[len] != ' ') {
            len++;
        }
        int n = snprintf(out, outsz, "%s%.*s",
                         name[0] == '/' ? "" : "/", (int)len, name);
        return (n >= 0 && (size_t)n < outsz);
    }
    return build_path(out, outsz, dir[0] ? dir : DEFAULT_DEVICE, name);
}

/**
 * @brief Handle the "cd" command: change the console working directory.
 *
 * With no argument the working directory is reset to the filesystem root.
 *
 * @param dir     Working-directory buffer (64 bytes), updated in place.
 * @param command Full command line.
 */
void console_cd(char *dir, char *command) {
    char *arg = get_argument(command, 1);
    if(!arg) {
        memset(dir, 0, 64);
        return;
    }
    if(!build_path(senddir, sizeof(senddir), dir, arg)) {
        printf("Path too long\n");
        return;
    }
    if(vfs_cd(senddir)) {
        memset(dir, 0, 64);
        strncpy(dir, senddir, 63);
    } else {
        printf("cd %s: directory not found\n", senddir);
    }
}

/**
 * @brief Handle the "start" command: load and run a program from disk.
 *
 * Blocks until the spawned process stops, then reaps it. The program name is
 * resolved against the console working directory (see resolve_path()).
 *
 * @param command Full command line ("start <prog> [args...]").
 */
void console_start(char *command) {
    char *prog = get_argument(command, 1);
    if(!prog || !*prog) {
        printf("start: missing program name\n");
        return;
    }
    if(!resolve_path(senddir, sizeof(senddir), prog)) {
        printf("start: path too long\n");
        return;
    }

    char *arguments = kmalloc(128);
    memset(arguments, 0, 128);
    char *rest = get_argument(command, 2);
    if(rest) {
        strncpy(arguments, rest, 127);
        arguments[127] = 0;
    }

    int procn = start_proc(senddir, arguments);
    if(procn != PROC_STOPPED) {
        while(proc_state(procn) != PROC_STOPPED) {
            /* busy-wait for the child to exit */
        }
        remove_proc(procn);
        printf("\n");
    }
}

/**
 * @brief Dump the contents of an open file to the console.
 *
 * @param f File opened for reading; directories and unopened files are
 *          rejected with a message.
 */
void print_file(file *f) {
    if(f->type == FS_NULL) {
        printf("Cannot open file\n");
        return;
    }

    if((f->type & FS_DIR) == FS_DIR) {
        printf("Cannot display content of directory.\n");
        return;
    }

    while(f->eof != 1) {
        char buf[512];
        memset(buf, 0, sizeof(buf));
        vfs_file_read(f, buf);

        for(int i = 0; i < 512; i++) {
            printf("%c", buf[i]);
            if(i > 0 && i % 56 == 0) {
                printf("\n");
            }
        }
    }
}

/**
 * @brief Handle the "read" command: print a file.
 *
 * The file name is resolved against the console working directory
 * (see resolve_path()).
 *
 * @param command Full command line ("read <file>").
 */
void console_read(char *command) {
    char *arg = get_argument(command, 1);
    if(!arg || !*arg) {
        printf("read: missing file name\n");
        return;
    }
    if(!resolve_path(senddir, sizeof(senddir), arg)) {
        printf("read: path too long\n");
        return;
    }
    file *f = vfs_file_open(senddir, "r");
    if(f->type != FS_FILE) {
        printf("read: file %s not found\n", senddir);
    } else {
        print_file(f);
    }
    vfs_file_close(f);
}

/**
 * @brief Play a short square-wave tone through the AC97 codec ("beep").
 */
static void console_beep(void) {
    uint16_t *audio_buffer = (uint16_t *)kmalloc(BEEP_SAMPLES * sizeof(uint16_t));
    for(int i = 0; i < BEEP_SAMPLES; i++) {
        audio_buffer[i] = (i % 100 < 50) ? 10000 : -10000;
    }
    /* The AC97 driver plays from this buffer via DMA and owns it afterwards. */
    ac97_play_buffer((uint8_t *)audio_buffer, BEEP_SAMPLES * sizeof(uint16_t));
}

/**
 * @brief Print the enumerated PCI device table ("pci").
 */
static void console_pci(void) {
    pci_dump();
}

/**
 * @brief Print the network interface's MAC, link state and frame counters ("net").
 */
static void console_net(void) {
    if(!e1000_present()) {
        printf("net: no network interface\n");
        return;
    }
    uint8_t m[6];
    e1000_mac(m);
    printf("e1000: %02x:%02x:%02x:%02x:%02x:%02x  link %s  rx %u  tx %u\n",
           m[0], m[1], m[2], m[3], m[4], m[5],
           e1000_link_up() ? "up" : "down",
           e1000_rx_count(), e1000_tx_count());

    if(net_is_up()) {
        const net_ipv4_t *c = net_config();
        char ip[16], mask[16], gw[16], dns[16];
        printf("  ip %s  mask %s\n", net_ip_str(c->ip, ip), net_ip_str(c->mask, mask));
        printf("  gw %s  dns %s\n", net_ip_str(c->gw, gw), net_ip_str(c->dns, dns));
        printf("  dhcp %s (server %s, lease %us)\n",
               dhcp_state_name(), net_ip_str(c->server, ip), c->lease_secs);
    } else {
        printf("  dhcp %s (no lease yet)\n", dhcp_state_name());
    }
}

/**
 * @brief Parse and execute one console command line.
 *
 * Recognised commands: help, mem, ps, ls, cd, start, read, beep, pci, net,
 * poweroff, reboot. Unknown input produces a "not found" message.
 *
 * @param buf NUL-terminated command line (without the trailing newline).
 */
void console_exec(char *buf) {
    if(strcmp(buf, "help") == 0) {
        printf("help     - shows help\n"
               "mem      - prints RAM info\n"
               "ps       - prints process information\n"
               "ls       - lists the current directory\n"
               "cd       - changes directory\n"
               "start    - runs a program\n"
               "read     - prints a file\n"
               "beep     - plays a tone\n"
               "pci      - lists PCI devices\n"
               "net      - network interface status\n"
               "poweroff - powers the machine off (ACPI)\n"
               "reboot   - reboots the machine\n");
    } else if(strcmp(buf, "pci") == 0) {
        console_pci();
    } else if(strcmp(buf, "net") == 0) {
        console_net();
    } else if(strcmp(buf, "poweroff") == 0) {
        printf("Powering off.\n");
        exit_qemu(0);
    } else if(strcmp(buf, "reboot") == 0) {
        printf("Rebooting.\n");
        acpi_reboot();
    } else if(strcmp(buf, "mem") == 0) {
        print_meminfo();
    } else if(strcmp(buf, "ps") == 0) {
        print_procs();
    } else if(strcmp(buf, "ls") == 0) {
        if(dir[0] == 0) {
            vfs_ls();
        } else {
            vfs_ls_dir(dir);
        }
    } else if(strncmp(buf, "cd", 2) == 0) {
        console_cd(dir, buf);
    } else if(strncmp(buf, "start", 5) == 0) {
        console_start(buf);
    } else if(strncmp(buf, "read", 4) == 0) {
        console_read(buf);
    } else if(strncmp(buf, "beep", 4) == 0) {
        console_beep();
    } else {
        printf("Command '%s' not found.\n", buf);
    }
}

/**
 * @brief Interactive read-eval-print loop for the kernel debug console.
 *
 * Reads keystrokes from the keyboard, echoes them, and runs each line through
 * console_exec() when Enter is pressed. Never returns.
 */
void kmain_console(void) {
    char cmdbuf[256];
    int i = 0;
    printf("> ");
    while(1) {
        char c = keyboard_get_lastkey();
        if(!c) {
            continue;
        }
        keyboard_invalidate_lastkey();
        if(c == '\n') {
            cmdbuf[i] = 0;
            printf("\n");
            console_exec(cmdbuf);
            i = 0;
            printf("> ");
        } else if(c == '\b') {
            if(i > 0) {
                i--;
                printf("\b \b");
            }
        } else if(i < (int)sizeof(cmdbuf) - 1) {
            cmdbuf[i++] = c;
            printf("%c", c);
        }
    }
}
