/**
 * @file apps/microui/mkfont.c
 * @brief Host tool: bake the ASCII range of unifont.sfn into an 8x16 bitmap
 *        table for the ring-3 microui runtime.
 *
 * Runs on the build machine, not in the OS. The kernel draws its console and
 * its own microui desktop with ssfn.h out of the 1.2 MiB unifont.sfn blob
 * linked into the image; a ring-3 program cannot afford either (the blob is
 * bigger than every app in apps/ put together, and the RAM disk is 8 MiB), so
 * the 95 printable ASCII glyphs are rasterised here instead -- 1520 bytes of
 * .rodata in the app, and text that matches the desktop's glyph for glyph.
 *
 * Unifont is natively an 8x16 bitmap font, so this is an extraction rather
 * than a rendering: ssfn's console renderer hands back exactly the cell the
 * font stores, with no scaling and nothing to round.
 *
 *   mkfont <unifont.sfn> <out.h>
 *
 * Built -m32 because ssfn.h parses the font through the kernel's own
 * <types.h>, whose size_t is `unsigned int`; the repo already needs a 32-bit
 * host toolchain for every app here.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* The console renderer writes 8-bit palette indices, which is what this wants:
 * one byte per pixel, foreground 1 and background 0. CLEARBG is not just for
 * the blank fill -- without it the PALETTE path writes ssfn_bg for *set*
 * pixels (an upstream slip in the vendored header), so the glyph comes out
 * empty. With it, set pixels take ssfn_fg and the cell is cleared for free. */
#define SSFN_CONSOLEBITMAP_PALETTE
#define SSFN_CONSOLEBITMAP_CLEARBG
/* By path, not by -I: the repo root also holds the kernel's own <stdlib.h>
 * and friends, which would shadow the host's for the rest of this file. */
#include "../../ssfn.h"

#define CELL_W 8
#define CELL_H 16
#define FIRST  32
#define LAST   126

/* Scratch wide enough that a glyph overhanging its cell cannot run off the
 * end: ssfn_putc clips against ssfn_dst_w/h, which are set to the cell. */
static unsigned char cell[64 * 64];

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: %s <unifont.sfn> <out.h>\n", argv[0]);
        return 2;
    }

    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror(argv[1]); return 1; }
    if (fseek(f, 0, SEEK_END) != 0) { perror("fseek"); return 1; }
    long size = ftell(f);
    if (size <= 0) { fprintf(stderr, "%s: empty\n", argv[1]); return 1; }
    rewind(f);
    unsigned char *blob = malloc((size_t) size);
    if (!blob) { fprintf(stderr, "out of memory\n"); return 1; }
    if (fread(blob, 1, (size_t) size, f) != (size_t) size) {
        fprintf(stderr, "%s: short read\n", argv[1]);
        return 1;
    }
    fclose(f);

    ssfn_font = (ssfn_font_t *) blob;
    if (memcmp(ssfn_font->magic, "SSFN", 4) != 0) {
        fprintf(stderr, "%s: not an SSFN font\n", argv[1]);
        return 1;
    }

    FILE *o = fopen(argv[2], "w");
    if (!o) { perror(argv[2]); return 1; }

    fprintf(o,
        "/* Generated by apps/microui/mkfont.c from %s -- do not edit.\n"
        " * The printable ASCII range of GNU Unifont as an %dx%d bitmap, one\n"
        " * byte per row, bit 0x80 leftmost. Unifont is dual-licensed GPLv2+\n"
        " * with the font-embedding exception, and OFL 1.1; see\n"
        " * apps/microui/README.md. */\n"
        "#pragma once\n\n"
        "#define MUI_FONT_W     %d\n"
        "#define MUI_FONT_H     %d\n"
        "#define MUI_FONT_FIRST %d\n"
        "#define MUI_FONT_LAST  %d\n\n"
        "static const unsigned char mui_font[%d][%d] = {\n",
        argv[1], CELL_W, CELL_H, CELL_W, CELL_H, FIRST, LAST,
        LAST - FIRST + 1, CELL_H);

    int missing = 0;
    for (int ch = FIRST; ch <= LAST; ch++) {
        memset(cell, 0, sizeof cell);
        ssfn_dst_ptr   = cell;
        ssfn_dst_pitch = sizeof cell / 64;
        ssfn_dst_w     = CELL_W;
        ssfn_dst_h     = CELL_H;
        ssfn_fg        = 1;
        ssfn_bg        = 0;
        ssfn_x         = 0;
        ssfn_y         = 0;
        if (ssfn_putc((unsigned int) ch) != SSFN_OK) {
            fprintf(stderr, "mkfont: no glyph for 0x%02x\n", ch);
            missing++;
        }

        fprintf(o, "    {");
        for (int y = 0; y < CELL_H; y++) {
            unsigned row = 0;
            for (int x = 0; x < CELL_W; x++)
                if (cell[y * ssfn_dst_pitch + x])
                    row |= 0x80u >> x;
            fprintf(o, "%s0x%02x", y ? "," : "", row);
        }
        fprintf(o, "},  /* '%c' */\n", ch);
    }
    fprintf(o, "};\n");
    if (fclose(o) != 0) { perror(argv[2]); return 1; }

    return missing ? 1 : 0;
}
