all:
	$(MAKE) -C 01
	$(MAKE) -C hello
	$(MAKE) -C example
	$(MAKE) -C mem
	$(MAKE) -C lua
	$(MAKE) -C fault

clean:
	$(MAKE) -C 01 clean
	$(MAKE) -C hello clean
	$(MAKE) -C example clean
	$(MAKE) -C mem clean
	$(MAKE) -C lua clean
	$(MAKE) -C fault clean

.phony: all clean
