all:
	$(MAKE) -C 01
	$(MAKE) -C hello
	$(MAKE) -C hello-cpp
	$(MAKE) -C hello-stl
	$(MAKE) -C hello-str
	$(MAKE) -C hello-map
	$(MAKE) -C hello-umap
	$(MAKE) -C hello-set
	$(MAKE) -C hello-thread
	$(MAKE) -C hello-pthread
	$(MAKE) -C hello-theap
	$(MAKE) -C hello-tls
	$(MAKE) -C hello-qt
	$(MAKE) -C example
	$(MAKE) -C mem
	$(MAKE) -C lua
	$(MAKE) -C fault
	$(MAKE) -C cc
	$(MAKE) -C zsh
	$(MAKE) -C calc
	$(MAKE) -C clock
	$(MAKE) -C doom
	$(MAKE) -C chipnomad

clean:
	$(MAKE) -C 01 clean
	$(MAKE) -C hello clean
	$(MAKE) -C hello-cpp clean
	$(MAKE) -C hello-stl clean
	$(MAKE) -C hello-str clean
	$(MAKE) -C hello-map clean
	$(MAKE) -C hello-umap clean
	$(MAKE) -C hello-set clean
	$(MAKE) -C hello-thread clean
	$(MAKE) -C hello-pthread clean
	$(MAKE) -C hello-theap clean
	$(MAKE) -C hello-tls clean
	$(MAKE) -C hello-qt clean
	$(MAKE) -C example clean
	$(MAKE) -C mem clean
	$(MAKE) -C lua clean
	$(MAKE) -C fault clean
	$(MAKE) -C cc clean
	$(MAKE) -C zsh clean
	$(MAKE) -C calc clean
	$(MAKE) -C clock clean
	$(MAKE) -C doom clean
	$(MAKE) -C chipnomad clean

.phony: all clean
